#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-apicv-deployment
spec:
  selector:
    matchLabels:
      app: node-apicv-server
  replicas: 1
  template:
    metadata:
      labels:
        app: node-apicv-server
    spec:
      containers:
      - name: node-apicv-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/frankisoft/node-apicv:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: node-apicv-service
  name: node-apicv-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: node-apicv-server
  type: LoadBalancer
